services:
  app:
    image: 'stockexchange-img'
    build:
      context: .
    container_name: stockexchange
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exchangedb
      - SPRING_DATASOURCE_USERNAME=stockexchange
      - SPRING_DATASOURCE_PASSWORD=stockexchange
    ports:
      - 8080:8080

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exchangedb
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/scripts:/docker-entrypoint-initdb.d
