spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/exchangedb
        username: stockexchange
        password: stockexchange
    kafka:
        bootstrap-servers: "localhost:29092"